//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_PHONE_SERVICE.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(export_bill))]
    [KnownType(typeof(role))]
    
    public partial class user
    {
        public user()
        {
            this.export_bill = new HashSet<export_bill>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int id_role { get; set; }
    	[DataMember]
        public string name { get; set; }
    	[DataMember]
        public string email { get; set; }
    	[DataMember]
        public string password { get; set; }
    	[DataMember]
        public string phone_number { get; set; }
    	[DataMember]
        public string address { get; set; }
    
    	[DataMember]
        public virtual ICollection<export_bill> export_bill { get; set; }
    	[DataMember]
        public virtual role role { get; set; }
    }
}
